In [4]:
import pickle 
from sklearn.externals import joblib
import pandas as od
from sklearn.preprocessing import MinMaxScaler
import keras
import pandas as pd

In [4]:
! pip install keras

Collecting keras
  Using cached https://files.pythonhosted.org/packages/ad/fd/6bfe87920d7f4fd475acd28500a42482b6b84479832bdc0fe9e589a60ceb/Keras-2.3.1-py2.py3-none-any.whl
Collecting keras-applications>=1.0.6 (from keras)
  Using cached https://files.pythonhosted.org/packages/71/e3/19762fdfc62877ae9102edf6342d71b28fbfd9dea3d2f96a882ce099b03f/Keras_Applications-1.0.8-py3-none-any.whl
Requirement already satisfied: six>=1.9.0 in /home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from keras) (1.11.0)
Requirement already satisfied: numpy>=1.9.1 in /home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from keras) (1.15.4)
Requirement already satisfied: pyyaml in /home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from keras) (5.3.1)
Requirement already satisfied: h5py in /home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from keras) (2.8.0)
Requirement already satisfied: scipy>=0.14 in /home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from keras) (1.1.0)
Collecting keras-preprocessing>=1.0.5 (from keras)
  Using cached https://files.pythonhosted.org/packages/28/6a/8c1f62c37212d9fc441a7e26736df51ce6f0e38455816445471f10da4f0a/Keras_Preprocessing-1.1.0-py2.py3-none-any.whl
fastai 1.0.60 requires nvidia-ml-py3, which is not installed.
Installing collected packages: keras-applications, keras-preprocessing, keras
Successfully installed keras-2.3.1 keras-applications-1.0.8 keras-preprocessing-1.1.0
You are using pip version 10.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

In [5]:
mdl=joblib.load('loan_model.pkl')

In [9]:
df=pd.read_csv('production_data_loan.csv')
df=pd.get_dummies(df)
df.head()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Gender_Female,Gender_Male,Married_No,Married_Yes,...,Dependents_1,Dependents_2,Dependents_3+,Education_Graduate,Education_Not Graduate,Self_Employed_No,Self_Employed_Yes,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban
0,0.670769,6675.532232,769.282059,180.0,1.0,0.0,0,1,0,1,...,0,0,1,1,0,0,1,0,1,0
1,0.214215,9619.647456,516.424109,380.0,0.0,0.0,1,0,1,0,...,0,0,0,1,0,0,1,0,0,1
2,0.821612,9727.918603,723.193873,44.0,1.0,0.0,1,0,1,0,...,0,1,0,1,0,1,0,0,1,0
3,0.449371,9909.411865,898.895443,60.0,0.0,1.0,1,0,1,0,...,0,0,1,0,1,0,1,0,0,1
4,0.220604,2460.762401,449.185004,36.0,0.0,1.0,1,0,0,1,...,1,0,0,0,1,0,1,0,0,1

In [15]:
X=df.drop(['Loan_Status'], axis=1)
sc=MinMaxScaler()
X_test=sc.fit_transform(X)
X_test[1]

array([0.12174487, 0.9690996 , 0.5708939 , 1.        , 0.        ,
       1.        , 0.        , 1.        , 0.        , 1.        ,
       0.        , 0.        , 0.        , 1.        , 0.        ,
       0.        , 1.        , 0.        , 0.        , 1.        ])

In [19]:
y_pred=mdl.predict(X_test)
y_pred=(y_pred > 0.52)
data=pd.DataFrame(y_pred, columns=['Status'])
data=data.replace({True: 'Accepted', False: 'Rejected'})
data

/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ipykernel/__main__.py:2: RuntimeWarning: invalid value encountered in greater
  from ipykernel import kernelapp as app

      Status
0   Rejected
1   Rejected
2   Rejected
3   Rejected
4   Rejected
5   Accepted
6   Rejected
7   Rejected
8   Rejected
9   Accepted
10  Rejected
11  Rejected
12  Rejected
13  Rejected